#!/bin/bash

#ssh-ec2 parameter-completion

_find_ec2_keywords ()
{
  echo $(cat /var/aws-cli/cache/describe-instances.d/ec2-desc.json \
    | jq '[.name, .privateIpAddress, .privateDnsName, .instanceId]' \
    | grep -v "\[" \
    | grep -v "\]" \
    | sed -e "s|,$||g" \
    | sed -e "s| |_|g" \
    | sed -e "s|^__| |g" \
    | grep -v "null" \
    | xargs echo)
}

_aws_ec2_keywords ()
{
  local cur

  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]}
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  case "$cur" in
    -*)
    ;;

    *)
        EC2_KEYWORDS=$(_find_ec2_keywords)
        COMPREPLY=( $( compgen -W "${EC2_KEYWORDS}" -- $cur) )
    ;;
  esac

  return 0
}

complete -F _aws_ec2_keywords ssh-ec2
