#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

if [ "$#" -ne 1 ]; then
    echo "usage: ssh-ec2 <hostname | instance-id | Name-Tag>" >&2
    exit 1;
fi

_SEARCH_TERM=$(echo -n $1 | sed -e 's|_| |g')
_EC2_HOSTNAME=$(cat /var/aws-cli/cache/describe-instances.d/ec2-desc.json | jq --arg NAME "${_SEARCH_TERM}" 'select(.["name"] == $NAME) | .privateDnsName' | xargs echo)

if [ -z "${_EC2_HOSTNAME// }"  ]; then
    #${_SEARCH_TERM} is not a 'Name' tag, check hostname
    _EC2_HOSTNAME=$(cat /var/aws-cli/cache/describe-instances.d/ec2-desc.json | jq --arg NAME "${_SEARCH_TERM}" 'select(.privateDnsName == $NAME) | .privateDnsName' | xargs echo)
fi

if [ -z "${_EC2_HOSTNAME// }"  ]; then
    #${_SEARCH_TERM} is not a 'Name' tag or HostName, check IP-Address
    _EC2_HOSTNAME=$(cat /var/aws-cli/cache/describe-instances.d/ec2-desc.json | jq --arg NAME "${_SEARCH_TERM}" 'select(.privateIpAddress == $NAME) | .privateDnsName' | xargs echo)
fi

if [ -z "${_EC2_HOSTNAME// }"  ]; then
    #${_SEARCH_TERM} is not a 'Name' tag or HostName, check IP-Address
    _EC2_HOSTNAME=$(cat /var/aws-cli/cache/describe-instances.d/ec2-desc.json | jq --arg NAME "${_SEARCH_TERM}" 'select(.instanceId == $NAME) | .privateDnsName' | xargs echo)
fi

if [ -z "${_EC2_HOSTNAME// }"  ]; then
    #${_SEARCH_TERM} was not found! send an error
	echo "Cannot find hostname for ${_SEARCH_TERM}" >&2
	exit 2;
fi

echo -e "running command:: ssh ${_EC2_HOSTNAME}" >&2

ssh ${_EC2_HOSTNAME}
